name: cast

services:
  nginx:
    build:
      context: ..
      dockerfile: ./docker/nginx.prod.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - client
      - server
    networks:
      - public
      - internal

  client:
    build:
      context: ..
      dockerfile: ./docker/client.Dockerfile
      args:
        NEXT_PUBLIC_BACK_END_API_URL: https://casyu.me/api
        NEXT_PUBLIC_FRONT_END_URL: https://casyu.me
    environment:
      PORT: 80
    depends_on:
      - server
    networks:
      - internal

  server:
    build:
      context: ..
      dockerfile: ./docker/server.Dockerfile
    environment:
      MONGO_URI: mongodb://mongodb:27017
      PORT: 8080
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - internal

networks:
  public:
  internal:
    internal: true

volumes:
  mongodb_data:
  mongodb_config:
