name: Remote docker compose

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on remote host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.RN_SSH_HOST }}
          username: ${{ secrets.RN_SSH_USER }}
          key: ${{ secrets.RN_SSH_PRIVATE_KEY }}
          script: |
            set -eu
            mkdir -p /etc/nginx/ssl
            umask 077
            echo "${{ secrets.ORIGIN_CERT_B64 }}" | base64 -d | tee /etc/nginx/ssl/casyu.me.origin.crt > /dev/null
            echo "${{ secrets.ORIGIN_KEY_B64 }}"  | base64 -d | tee /etc/nginx/ssl/casyu.me.origin.key > /dev/null
            chmod 600 /etc/nginx/ssl/example.com.origin.key
            cd /root/projects/cast
            git pull --ff-only
            bun docker:prod
